### ISSUE TITLE
Glue packages

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/decerver-interfaces#20]
Glue modules (blockchain interfaces) are used both in the decerver and in the epm cli.  
The difference being the ones in the decerver must return javascript friendly objects while those 
used by epm should not.
Ideally, any blockchain wrapper that is written will come with both parts, so they can be used readily either by decerver or epm. The easiest way to do this is probably to write the golang ready library (ie for epm) and then wrap that with the javascript ready module (for ate).

We should probably also pull the glue packages out of `decerver-interfaces` and put them in a `glue` repo with `blockchains` and `filesystems` directories.

@androlo and I talked about this briefly in slack and he may have some alternative ideals for structuring this.

**Comment by androlo** [comment]
modules has been moved out of this repo. closing.
