### ISSUE TITLE
Big changes in decerver/interfaces/modules

### ISSUE THREAD

**Issue by androlo** [eris-ltd/decerver-interfaces#29]
These repos are changing. There will be two repositories in the future: decerver and decerver-modules. Decerver-interfaces is going away. Modules has already been moved, and will be put in decerver-modules. Interfaces will be put in an 'interfaces' folder in decerver.

There will be new module-related issues in the module repository, which will link to the issues here. This repo should therefore be around until those issues has been resolved, so I won't delete it for a while. I will add decerver issues for interface related stuff in the same way.

**Comment by androlo** [comment]
decerver
decerver-client
decerver-modules
decerver-admin

This would be the complete list going forward. decerver is the backend. client is the client. modules are the modules. admin is the admin stuff and should maybe be moved into decerver client?

**Comment by ebuchman** [comment]
makes sense. admin in the client seems reasonable.
i will replicate with epm ie `epm/`, `epm/interfaces`, and `epm-modules`
